---
# Kevin M. Meziere <kmeziere@jpcatholic.com>
# Copyright 2015, John Paul the Great Catholic University

- name: Lookup version of Snarl
  shell: "pkgin list | grep fifo-snarl | awk '{print $1}'"
  register: snarl_version_installed
  changed_when: "snarl_version_installed.stdout != '{{ snarl_version_required }}'"
  ignore_errors: True

- name: Check for Project Fifo GPG Key
  shell: "gpg --keyring /opt/local/etc/gnupg/pkgsrc.gpg --fingerprint | grep '{{ fifo_gpg_keyid }}'"
  register: fifo_gpg_key
  changed_when: fifo_gpg_key.rc != 0
  ignore_errors: True
  when: snarl_version_installed.stdout != "{{ howl_version_required }}"

- name: Install Project Fifo GPG Key
  shell: "curl https://project-fifo.net/fifo.gpg | gpg --primary-keyring /opt/local/etc/gnupg/pkgsrc.gpg --import"
  when: fifo_gpg_key.rc != 0

- name: Install/Upgrade Snarl
  command: "pkg_add -u http://release.project-fifo.net/pkg/'{{ snarl_release }}'/'{{ snarl_version_required }}'.tgz"
  when: snarl_version_installed.stdout != "{{ snarl_version_required }}"

- name: Configure Snarl
  template: src=snarl-config.j2 dest=/opt/local/fifo-snarl/etc/snarl.conf backup=yes
  notify: Bounce Snarl

- name: Enable EPMD
  service: name=epmd state=started enabled=yes
  when: "'snarl_no_start' not in {{ group_names }}"

- name: Enable Snarl
  service: name=snarl state=started enabled=yes
  when: "'snarl_no_start' not in group_names"
  register: snarl_service_start

- name: Pause for Snarl Startup
  pause: seconds=20
  when: snarl_service_start.changed != False